[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask-cors==4.0.1",
    "flask==3.0.3",
    "sqlalchemy==2.0.31",
    "psycopg2-binary>=2.9.10",
    "requests>=2.32.5",
]
